# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ab34be02ec5197f1ca4ed54c4aa596c855769ee86893ea4453cdb46f3938dc55673b589beef746aaed82b9421260597d9ecf2dd92af25d922ac4c4b38c3fd03

test:
  secret_key_base: 592aa73ecfc28878435e0263464a1d18898a9c9267c97ed2c0165fc90eee72315271c66061dd60576bd83464ec6a898fc0a228c2998b2f3955d0bb8874a2512e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
